# 应用服务 WEB 访问端口
server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
    nacos:
      username: nacos
      password: 123321
      discovery:
        server-addr: 118.31.39.88:8848
      config:
        server-addr: 118.31.39.88:8848
        username: nacos
        password: 123321
        group: DEFAULT_GROUP
        file-extension: yml
        namespace: public
  application:
    name: mall-member

