# 应用服务 WEB 访问端口
server:
  port: 8084
spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.39.88:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123321
  cloud:
    nacos:
      username: nacos
      password: 123321
      discovery:
        server-addr: 118.31.39.88:8848
  application:
    name: mall-product
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


